version: '3.8'

services:
  # Контейнер с базой данных PostgreSQL
  postgres:
    image: postgres:14-alpine  # Оптимизированный образ PostgreSQL
    container_name: ssh_client_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных БД
    expose:
      - '5432'
    restart: always
    networks:
      - app_network

  # Контейнер с Java приложением (Spring Boot)
  app:
    build:
      context: ./server  # Сборка приложения из текущей директории
    container_name: ssh_client_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    expose:
      - '8080'
    restart: always
    networks:
      - app_network

  # Контейнер с Nginx (прокси-сервер)
  nginx:
    build:
      context: .  # Контекст сборки — корень проекта
      dockerfile: nginx/Dockerfile
    container_name: proxy_nginx
    ports:
      - '80:80'
      - "445:445"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
      - postgres
    networks:
      - app_network

# Определение сети
networks:
  app_network:
    driver: bridge

# Определение томов для хранения данных БД
volumes:
  postgres_data:
