version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: ssh_client_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    networks:
      - app_network
    restart: always

  app:
    build: .
    container_name: ssh_client_app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    restart: always

networks:
  app_network:
    driver: bridge
